name: Henfam
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_switch: ^0.0.1
  intl: ^0.16.1
  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  google_maps_flutter: ^0.5.28+1
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.17
  geolocator: ^5.3.2+2
  stripe_payment: ^1.0.7
  cloud_functions: ^0.5.0
  url_launcher: ^5.5.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.3
  test: ^1.15.2
  bloc_test: ^7.0.0
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/eggScore.png
    - assets/egglogo.png
    - assets/hen.png
    - assets/location_pin.png
    - assets/activity5.png
    - assets/activity4.png
    - assets/activity3.png
    - assets/activity2.png
    - assets/activity1.png
    - assets/oishiibowl.png
    - assets/oishii_bowl_pic.png
    - assets/oishii_bowl_pic1.png
    - assets/kungfutea.png
    - assets/insomnia.png
    - assets/henProfileIcon.png
    - assets/profilePic.png
    - assets/beeperson.png
    - assets/beeperson@2x.png
    - assets/beeperson@3x.png
    - assets/man1.png
    - assets/man1@2x.png
    - assets/man1@3x.png
    - assets/man2.png
    - assets/man2@2x.png
    - assets/man2@3x.png
    - assets/woman1.png
    - assets/woman1@2x.png
    - assets/woman1@3x.png
    - assets/beelogo.png
    - assets/bowl.png
    - assets/ctb.png
